[package]
name = "crustls"
version = "0.1.0"
authors = ["Jacob Hoffman-Andrews <github@hoffman-andrews.com>"]
description = "C-to-rustls bindings"
edition = "2018"

[dependencies]
# Keep in sync with RUSTLS_CRATE_VERSION in lib.rs
rustls = "^0.19.0"
webpki = "0.21"
libc = "0.2"
env_logger = "0.8"
webpki-roots = "0.21"
sct = "0.6.0"

[dev_dependencies]
cbindgen = "*"

[lib]
name = "crustls"
crate-type = ["staticlib"]
