[package]
name = "crustls"
version = "0.3.0"
authors = ["Jacob Hoffman-Andrews <github@hoffman-andrews.com>"]
description = "C-to-rustls bindings"
edition = "2018"
links = "crustls"

[dependencies]
# Keep in sync with RUSTLS_CRATE_VERSION in lib.rs
rustls = { git = "https://github.com/ctz/rustls", rev = "361b0c95c37538274d6c567af61199c04cbcb765", features = [ "dangerous_configuration" ] }
webpki = "0.22"
libc = "0.2"
rustls-native-certs = "0.5.0"
sct = "0.7"
rustls-pemfile = "0.2.0"

[dev_dependencies]
cbindgen = "*"

[lib]
name = "crustls"
crate-type = ["lib", "staticlib"]
