name: test
permissions:
  contents: read
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        cc: [clang, gcc]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: make CC=${{ matrix.cc }} PROFILE=release test
      - run: NO_CHECK_CERTIFICATE= ./target/crustls-demo wrong.host.badssl.com /

  ensure-header-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: make src/crustls.h
      - run: git diff --exit-code

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: cargo fmt -- --check
