name: test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        cc: [clang, gcc]
    steps:
      - uses: actions/checkout@v2
      - run: make CC=${{ matrix.cc }} PROFILE=release test

  ensure-header-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make src/crustls.h
      - run: git diff

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - rustup toolchain install nightly
      - rustup component add miri
      - cargo install xargo
      - run: cargo +nightly miri test
